const samples=[
 {name:'가시성대',latin:'Pterois volitans',type:'외래종 · 주의',rarity:'희귀',risk:'주의',score:96,emoji:'🐠',points:120,description:'인도·태평양 원산의 외래종입니다. 화려한 무늬와 독성 가시가 특징이며, 국내 연안 생태계에 영향을 줄 수 있어요.',guide:'독성 가시가 있어 절대 만지지 마세요. 안전한 거리에서 사진만 기록하고, 위치 정보를 함께 저장해 주세요.'},
 {name:'노무라입깃해파리',latin:'Nemopilema nomurai',type:'위험종 · 주의',rarity:'보통',risk:'위험',score:92,emoji:'🪼',points:100,description:'대형 해파리로 촉수에 쏘이면 통증을 유발할 수 있습니다. 해수욕장과 어업 활동에 피해를 줄 수 있어요.',guide:'물에 떠 있거나 해변에 밀려온 개체도 만지지 마세요. 발견 위치를 기록하면 안전 지도 업데이트에 도움이 됩니다.'},
 {name:'현무암 주상절리',latin:'Basalt columnar joint',type:'지질 · 보전 관찰',rarity:'희귀',risk:'보전 관찰',score:94,emoji:'🪨',points:70,description:'화산 용암이 천천히 식으며 수축해 만들어진 기둥 모양의 지질 구조입니다. 해안의 형성 과정을 보여주는 소중한 기록이에요.',guide:'탐방로 안에서 관찰하고, 암석을 훼손하거나 가져가지 마세요. 사진 기록은 지질 유산 보전에 도움이 됩니다.'},
 {name:'큰입배스',latin:'Micropterus salmoides',type:'생태교란종 · 신고',rarity:'일반',risk:'신고 권장',score:89,emoji:'🐟',points:150,description:'토종 어류를 포식하는 대표적인 생태교란 어종입니다. 하천과 저수지의 생물 다양성을 위협할 수 있어요.',guide:'발견 위치와 사진을 저장해 주세요. 방류하거나 다른 장소로 옮기지 않는 것이 중요합니다.'}
];
const $=id=>document.getElementById(id);let current=samples[0],points=0,xp=0,level=1,records=0;const recorded=new Set();
function screen(name){['homeScreen','cameraScreen','resultScreen','bookScreen'].forEach(id=>$(id).classList.toggle('hidden',id!==name));}
function analyze(){current=samples[Math.floor(Math.random()*samples.length)];$('resultEmoji').textContent=current.emoji;$('previewEmoji').textContent=current.emoji;$('speciesName').textContent=current.name;$('latinName').textContent=current.latin;$('typeLabel').textContent=current.type;$('factType').textContent=current.type;$('rarity').textContent=current.rarity;$('rarityStatus').textContent=current.rarity;$('riskStatus').textContent=current.risk;$('confidence').textContent=current.score;$('description').textContent=current.description;$('guide').textContent=current.guide;$('rewardPoint').textContent=current.points;const gain=current.rarity==='희귀'?110:current.risk==='신고 권장'?100:80;$('rewardXp').textContent=gain;current.xp=gain;const feedback=current.type.includes('외래')?['외래종 감지','만지지 말고 위치를 기록해 주세요.','사진과 위치 정보는 외래종 확산 지도를 만드는 데 사용됩니다.']:current.type.includes('교란')?['생태교란종 감지','방류·이동하지 말고 발견 장소를 저장해 주세요.','토종 생물 보호를 위해 담당 기관의 관찰 자료로 활용될 수 있습니다.']:current.type.includes('위험')?['위험종 감지','안전거리를 유지하고 접촉하지 마세요.','사람과 반려동물의 접근을 막고, 필요하면 해변 안전요원에게 알려주세요.']:['지질 보전 안내','탐방로 안에서 관찰해 주세요.','암석을 훼손하거나 가져가지 않는 것이 지질 유산을 지키는 방법입니다.'];$('feedbackTitle').textContent=feedback[0];$('feedbackAction').textContent=feedback[1];$('feedbackDetail').textContent=feedback[2];$('feedbackCard').className='feedback-card '+(current.type.includes('지질')?'geo':'alert');screen('resultScreen');}
function book(){const list=$('bookList'), found=samples.filter(s=>recorded.has(s.name));list.innerHTML=(found.length?found.map(s=>`<article class="entry"><div class="emoji">${s.emoji}</div><section><p>${s.type}</p><b>${s.name}</b><small>희귀도: ${s.rarity} · 위험도: ${s.risk}</small></section><span class="badge">${s.rarity}</span></article>`).join(''):'<article class="entry locked"><div class="emoji">?</div><section><p>도감이 비어 있어요</p><b>첫 탐험을 시작해 보세요</b><small>사진을 기록하면 도감이 열립니다</small></section></article>')+`<article class="entry locked"><div class="emoji">?</div><section><p>아직 발견하지 못했어요</p><b>미지의 해양 생물</b><small>해안 탐험에서 찾아보세요</small></section></article>`;screen('bookScreen');}
$('openCamera').onclick=() => screen('cameraScreen');$('cameraNav').onclick=()=>screen('cameraScreen');$('closeCamera').onclick=()=>screen('homeScreen');$('demoScan').onclick=analyze;$('fileInput').onchange=e=>{if(e.target.files[0])analyze()};$('cameraInput').onchange=e=>{if(e.target.files[0])analyze()};$('backHome').onclick=()=>screen('homeScreen');$('homeNav').onclick=()=>screen('homeScreen');$('showBook').onclick=book;$('bookNav').onclick=book;$('bookBack').onclick=()=>screen('homeScreen');
$('saveRecord').onclick=()=>{if(recorded.has(current.name)){ $('toast').textContent='이미 기록된 발견이에요. 새로운 종을 찾아보세요!';$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500);return;}recorded.add(current.name);points+=current.points;xp+=current.xp;records++;if(xp>=1000){xp-=1000;level++;$('toast').textContent=`레벨 업! 탐험가 레벨 ${level} 달성 🎉`;}else{$('toast').textContent=`+${current.points}P · +${current.xp}XP! ${current.name}이 도감에 기록됐어요.`;}$('pointTotal').textContent=points.toLocaleString();$('levelNumber').textContent=level;$('xpNow').textContent=xp;$('xpLeft').textContent=(1000-xp).toLocaleString();$('xpBar').style.width=`${xp/10}%`;$('missionCount').textContent=Math.min(records,5);$('badgeCount').textContent=`${Math.min(records,3)} / 6`;if(records===1){$('badges').innerHTML='<article><div>🐠</div><b>첫 발견</b><small>생물 1종 기록</small></article><article class="locked-badge"><div>?</div><b>바다 지킴이</b><small>위험종 안전 기록</small></article><article class="locked-badge"><div>?</div><b>희귀 추적자</b><small>희귀종 3종 기록</small></article>'}$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)};
